### PR TITLE
Add Mac support

### PR DESCRIPTION
**Pull request by blackeuler**
Still new to lisp but I needed this line to load the library on mac.

### CODE REVIEW

**Comment by HiPhish** [comment]
Looks good. If I want to add support for later versions in the future, would be it be enough if I just prepend the new version numbers to the list? Like this (hypothetical example):

```lisp
(define-foreign-library libcmark
  (:darwin (:or "libcmark.so.0.31.0.dylib" "libcmark.so.0.30.3.dylib" "libcmark.so.0.30.2.dylib" "libcmark.dylib"))
  (:unix (:or "libcmark.so.0.31.0" "libcmark.so.0.30.3"  "libcmark.so.0.30.2" "libcmark.so.0" "libcmark"))
  (:t (:default "libcmark")))
```

**Comment by HiPhish** [comment]
On a second though, is it correct that libraries on macOS contain `so` in their name? I don't have a Mac, but I would have expected the correct file names to be of the form `libcmark.0.30.2.dylib`. Can you please check?

**Comment by HiPhish** [comment]
I was too fast in merging this PR. Please file a merge request on [GitLab](https://gitlab.com/HiPhish/cl-cmark) instead with the following changes:

- Check that the library names are correct for macOS
- Update the change log accordingly, something like "Support for native macOS library" under "Added" should be enough
- Please elaborate on how to keep the list for macOS updated for the eventuality that you no longer want to contribute Mac support

I have undone the merge, it was my mistake to merge it that quickly.

**Comment by blackeuler** [comment]
Ok, I will do some research and open this again on gitlab.

**Pull request merged**
